apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component--qxjb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component--qxjb
    app.kubernetes.io/part-of: test-app-awnn
  name: test-component--qxjb
  namespace: appstudio-e2e-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component--qxjb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component--qxjb
    spec:
      containers:
      - image: quay.io/psturc/test-images:2cacc1cedff047b5a85ee33f69b8b1eb
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
